# Generated by Django 4.2.2 on 2023-07-10 19:41

from django.db import migrations, models
import django.db.models.deletion
import loans.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("copies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_date", models.DateTimeField(auto_now_add=True)),
                ("return_date", models.DateTimeField(default=loans.models.return_date)),
                ("was_returned", models.BooleanField(default=False)),
                (
                    "copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan",
                        to="copies.copy",
                    ),
                ),
            ],
        ),
    ]
