# Generated by Django 4.2.2 on 2023-07-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0001_initial"),
        ("loans", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="is_returned",
            new_name="was_returned",
        ),
        migrations.AlterField(
            model_name="loan",
            name="copy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loan",
                to="copies.copy",
            ),
        ),
    ]
